### PR TITLE
Correct license of new SDK gems

### PR DESCRIPTION
**Pull request by st0012**
Keep the old `sentry-raven` with `Apache-2`, but new gems should be `MIT`.

### CODE REVIEW

**Comment by timhaines** [comment]
Thanks @st0012!  💯

**Review by mitsuhiko — APPROVED** [review]

**Review by bruno-garcia — APPROVED** [review]
LGTM given that the repo is Apache 2: https://github.com/getsentry/sentry-ruby/blob/master/LICENSE

**Review by mitsuhiko — CHANGES_REQUESTED** [review]
Actually the desire was for this to be MIT licensed.

**Review by rhcarvalho — COMMENTED** [review]
Perhaps we could make LICENSE a symlink to `sentry-ruby/LICENSE.txt`, similar to how README is a symlink.
By removing the file I'm afraid it will remove the license information that GitHub publishes about the repo:

image

**Comment by st0012** [comment]
@rhcarvalho 👍 updated

**Review by rhcarvalho — APPROVED** [review]

**Comment by bruno-garcia** [comment]
Shouldn't those be licensed to sentry? It's with your github handle

**Comment by st0012** [comment]
@bruno-garcia good catch 👍 all updated

**Comment by st0012** [comment]
@mitsuhiko may I merge this?

**Pull request merged**
