### PR TITLE
Fix latency related nil error for Sidekiq Queues module span data

### LINKED ISSUE #2485: Calling `perform_inline` with Sidekiq job causes error in `set_span_data` because `enqueued_at` is nil.
### Issue Description

- After upgrading to 5.22.0 we are getting errors in `set_span_data` when calling `perform_inline`

### Reproduction Steps

In a Rails project with Sidekiq and `sentry-sidekiq` call `Job.perform_inline`

### Expected Behavior

Run the job like normal

### Actual Behavior

It throws error:
```sh
TypeError
nil can't be coerced into Float (TypeError)

 set_span_data(transaction, id: job["jid"], queue: queue, latency: ((Time.now.to_f - job["enqueued_at"]) * 1000).to_i, retry_count: job["retry_count"] || 0)
```

### Ruby Version

3.3.5

### SDK Version

5.22.0

### Integration and Its Version

Rails 7.1.5, Sidekiq 7.3.6

### Sentry Config

```ruby
SENTRY_FILTER = %i[
  params...
]

Sentry.init do |config|
  StaticPlatform.sentry_environment.try do |sentry_environment|
    config.environment = sentry_environment
  end
  config.breadcrumbs_logger = [:active_support_logger, :http_logger]
  config.traces_sample_rate = StaticPlatform.sentry_traces_sample_rate
  config.profiles_sample_rate = StaticPlatform.sentry_profiles_sample_rate
  config.propagate_traces = StaticPlatform.sentry_propagate_traces?

  # https://docs.sentry.io/platforms/ruby/guides/rails/data-management/sensitive-data/#scrubbing-data
  filter = ActiveSupport::ParameterFilter.new(
    SENTRY_FILTER
  )

  # Allow us to raise a custom error for Sidekiq workers to be retried without reporting to Sentry
  config.excluded_exceptions += ["ApplicationWorker::RetryItError"]

  config.before_send = lambda do |event, hint|
    filtered_event = filter.filter(event.to_hash)

    exception = hint[:exception]

    if exception.is_a?(RestClient::ExceptionWithResponse)
      filtered_event[:contexts][:exception_response_body] = exception.http_body
    elsif exception.is_a?(Faraday::Error)
      filtered_event[:contexts][:exception_response_body] = exception.response.present? ? exception.response[:body] : exception.to_s
    end
    filtered_event
  end
end
```

### PR DESCRIPTION
**Pull request by sl0thentr0py**
fixes #2485

### CODE REVIEW

**Review by solnic — APPROVED** [review]

**Comment by swistaczek** [comment]
Hey @solnic, could I request this one get published as it impacts our production services?

**Comment by sl0thentr0py** [comment]
@swistaczek I can release tomorrow

**Comment by swistaczek** [comment]
Thank you!

**Comment by sl0thentr0py** [comment]
Release is blocked due to CI issues with the ongoing jruby / jar-dependecies / psych mess.
https://github.com/ruby/psych/issues/700
https://github.com/getsentry/sentry-ruby/pull/2490

@solnic I'm OOO till next week now, could you maybe try to figure out and make a patch release?
Otherwise, @swistaczek please use the last version (5.21.0) for now or point your gem to github (master).

**Comment by solnic** [comment]
@sl0thentr0py sure, I'll figure it out and push a release

**Comment by solnic** [comment]
OK it looks like we are really blocked with jruby-head crashing during bundling, I don't think there's an easy workaround so I just opened a PR that removes jruby-header from CI where it was failing to unblock a new release. Once the PR is merged, I'll push a release.

**Comment by sl0thentr0py** [comment]
@swistaczek released 5.22.1 now

**Pull request merged**
