### PR TITLE
Fixup `Net::HTTP` breadcrumb url & span creation when `Net::HTTP.start` is used

### PR DESCRIPTION
**Pull request by ojab**
**Please keep these instructions in mind so we can review it more efficiently:**

Right now we're not recording URL and creating single span for all the requests.

## Description
Not sure if body addition is a welcome change and if 100 is a good length, but  it would be useful for us.

### CODE REVIEW

**Comment by ojab** [comment]
CI failure is unrelated and I will update changelog with PR number anyway, so sending to review.

**Comment by ojab** [comment]
OTOH breadcrumbs are already limiting max message size since https://github.com/getsentry/sentry-ruby/pull/1465/files, so limiting body size could be dropped

**Comment by st0012** [comment]
@ojab thanks for the PR. I think they're both good additions but we can't add those information directly as it may contain pii data. we should only add them when `Sentry.configuration.send_default_pii` is `true`, like

https://github.com/getsentry/sentry-ruby/blob/efcf170b5f6dd65c3b047825bddd8fde87fc6b7b/sentry-ruby/lib/sentry/interfaces/request.rb#L40-L44

**Comment by ojab** [comment]
Yeah, I saw that and guessed that only incoming stuff is counted as PII.
I'll make a change to save query & body only with `send_default_pii` probably tomorrow then.

**Comment by ojab** [comment]
Updated, CI is green.

**Comment by ojab** [comment]
Also pushed commit to fix tracing to multiple requests in a single connection.

**Comment by st0012** [comment]
@ojab it looks like you've made a few other changes to address different issues? since you're essentially rewriting the `Net::HTTP` patch, can you separate the changes for different issues/features? it'll help me review this more carefully, as it's an important feature of the SDK. thanks.

**Comment by st0012** [comment]
also, the feature and fixes will likely go out separately (feature in `4.9.0` while bug fixes in `4.8.x`, depending on the impact).

**Comment by ojab** [comment]
Left only bugfixes in this PR and moved query string & body addition along with fix for span name for `Sentry.configuration.send_default_pii = false` case to the new PR https://github.com/getsentry/sentry-ruby/pull/1642. Every change is split per-commit, so hope two PRs are ok.

**Comment by ojab** [comment]
Hey, any changes to be done here?

**Comment by st0012** [comment]
@ojab hey sorry I'm quite busy recently so haven't got time to check all the PRs yet.

**Review by st0012 — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
