### PR TITLE
Fix exception event sending failed

### LINKED ISSUE #2082: Event sending failed: source sequence is illegal/malformed utf-8
### Issue Description

(Similar to #1911 and #1992)

I got the error `Event sending failed: source sequence is illegal/malformed utf-8`.

Here is the log:
```
Event sending failed: source sequence is illegal/malformed utf-8
Unreported Event: ArgumentError: wrong number of arguments (given 2, expected 1)
exception happened in background worker: source sequence is illegal/malformed utf-8
```

### Reproduction Steps

Call `Sentry.capture_exception(exception)` with a long exception message containing multibyte characters.

### Expected Behavior

Event is sent to Sentry.

### Actual Behavior

Event isn't sent to Sentry.

### Ruby Version

3.1.4

### SDK Version

5.4.2

### Integration and Its Version

_No response_

### Sentry Config

```
Sentry.init do |config|
  config.dsn = ENV["SENTRY_DSN"]
  config.enabled_environments = %w[production development]
  config.breadcrumbs_logger = %i[sentry_logger active_support_logger http_logger]
  config.capture_exception_frame_locals = true
end
```

### PR DESCRIPTION
**Pull request by yujideveloper**
fixes #2082

### CODE REVIEW

**Comment by st0012** [comment]
Sorry for the delay. I'm not sure why there's no triggerable CI runs on this PR. I also found a few expected failures when pulled the branch locally. Would you mind rebasing it against `master` and push again?

**Comment by yujideveloper** [comment]
@st0012 
Thank you for your reply. I rebased it against master.

**Comment by yujideveloper** [comment]
I missed a syntax error in Ruby 2.4 ...
I fixed it.

**Comment by yujideveloper** [comment]
I improved test coverage.

**Comment by yujideveloper** [comment]
I resolved confilict.

**Review by st0012 — APPROVED** [review]
Thank you for the fix!

**Comment by st0012** [comment]
The tests failing are caused by latest Rails changes. I will fix them in a separate PR.

**Pull request merged**
