### PR TITLE
SDK should drop the event when any event processor returns nil

### PR DESCRIPTION
**Pull request by st0012**
This is something we should've supported but was missed.

### CODE REVIEW

**Comment by st0012** [comment]
@rhcarvalho can you give this a quick look today? thanks 😄

**Review by rhcarvalho — COMMENTED** [review]
Late LGTM 👍 

By the way, is the SDK implementing the same behavior for global event processors and `beforeSend`?

**Comment by st0012** [comment]
What're global event processors? I thought they're always attached to a scope? 

It's implemented with `before_send` though.

According to the documentation, there are 5 steps in the event pipeline:

1. If the SDK is disabled, Sentry discards the event right away.
2. The client samples events as defined by the configured sample rate. Events may be discarded randomly, according to the sample rate.
3. The scope is applied, using apply_to_event. The scope’s event processors are invoked in order.
4. Sentry invokes the before-send hook.
5. Sentry passes the event to the configured transport. The transport can discard the event if it does not have a valid DSN; its internal queue is full; or due to rate limiting, as requested by the server.


4 Is already implemented and this PR fixes 3.

**Comment by rhcarvalho** [comment]
Some SDKs have, in addition to event processors added to Scope, event processors on Client and global. Those event processors are the same type of functions as beforeSend, the difference being that there can be multiple of them.

Most integrations use event processors to modify or drop events.

If the Ruby SDK doesn't have other event processors, that's okay and I suggest keeping things simple and not adding anything more.

My question was in the sense to make sure we fixed all similar issues related to the behavior of dropping events, it seems we did. Thanks! 🙏

**Comment by st0012** [comment]
I see. Thanks for explaining 👍

**Pull request merged**
