### PR TITLE
fix: Fix changelog config in craft

### PR DESCRIPTION
**Pull request by BYK**
This is a fix up to https://github.com/getsentry/sentry-ruby/pull/1390#issuecomment-834143608

### CODE REVIEW

**Review by st0012 — APPROVED** [review]
Thanks! I'll make a release today so can test this soon 👍

**Comment by st0012** [comment]
@BYK the prepare failed: https://github.com/getsentry/sentry-ruby/runs/2526077118?check_suite_focus=true

```
[9:34:10 AM] Error: Changelog does not exist: "sentry-ruby/CHANGELOG.md"
```

I think the release workflow enters the sub-folder before running the command, so the `sentry-*` folder name is not actually needed? But if that's the case, there's no need to specify the `changelog` attribute after all? However, not having the `changelog` didn't work either 😕

**Comment by BYK** [comment]
Ehh, I see the issue now. Prepare operates on the `.craft.yml` directory whereas publish fetches the changelog directly from the repo, meaning it looks at the root dir. That said I'm surprised that prepare complains about the missing changelog. Let me check the code. You can revert this patch in the meantime to get the release going.

**Comment by BYK** [comment]
Okay, I see the reason now. I'll write a patch for Craft so when it is released, this should be good to go.

You may still need to define the changelog files as some have the `md` extension and some doesn't (or rather, fix that inconsistency? :)).

**Comment by st0012** [comment]
@BYK I think the inconsistency only exists in `sentry-delayed_job/.craft.yml`. But before I make any change again, how will the changelog pulling work now though? Like this?
- prepare - read what's specified in the `changelog` attribute from **project root**.
- publish - read what's specified in the `changelog` attribute from **project root**.

**Comment by BYK** [comment]
@st0012 nah, I'll make them relative to `.craft.yml` file as that's more sensible. During `publish`, we'll have to calculate the path from `.git` root which should be easy.

**Comment by st0012** [comment]
@BYK why can't `prepare` pass the absolute changelog path (no matter how it's computed) to the issue or wherever the intermedium state is stored, so this chagnelog path calculation only needs to be done once?
I think this will make debugging easier. Because if they're done separately, it'll always require the SDK developer and Sentry's OSS team to work together to debug the issue from end to end.

**Comment by BYK** [comment]
@st0012 craft is built around the assumption that it runs in the same directory as `.craft.yml` which also is the project root, which also is the `.git` root.

We need to break that assumption to support monorepos like this. That's why we are keeping the `.craft.yml` being the "project root" but don't assume it is the `.git` root, hence calculate the path for the changelog when we fetch it from the git repo on the fly. From a project maintainer, this is transparent: all they do is define everything relative to the project root and hence `.craft.yml` file.

**Comment by st0012** [comment]
@BYK I see. Is `sentry-ruby` the only monorepo that releases packages separately from each sub-folder?
I should mention that we're planning to:
1. unify all gem's release and have only 1 change log at the repo root
2. but for `sentry-raven`, it'll still be released on its own and have its changelog under `sentry-raven/`

Will this change cause any problem with the craft update you're making?

**Comment by st0012** [comment]
@BYK I see, thanks 👍 I'll wait for the craft update and make the release next week then.

**Pull request merged**
