### PR TITLE
Allow custom tags to be passed when using the ActiveSupport::ErrorReporter

### PR DESCRIPTION
**Pull request by BobbyMcWho**
## Description

Allows for passing tags within the ActiveRecord::ErrorReporter context, to properly be sent to Sentry. ~~I noticed that this file lacks spec coverage, should I add a spec file for it?~~

Q: `context[:tags]` or `context[:sentry_tags]` ?

### CODE REVIEW

**Review by st0012 — COMMENTED** [review]
Thanks for the PR 👍 
I think we can use `tags` first as I can't think of any potential conflicts yet.

Can you also add a few cases for it? For example:

- It works when `context[:tags]` is a Hash and doesn't mutates `context`
- It doesn't break when `context[:tags]` is a non-Hash

**Comment by BobbyMcWho** [comment]
@st0012 Added the suggested changes, mind approving the workflow runs?

**Comment by BobbyMcWho** [comment]
Alright @st0012, I believe cb032e9 should resolve the suite failures

**Comment by BobbyMcWho** [comment]
Is it just jruby that's failing now? Is it the new jruby release?

**Review by st0012 — APPROVED** [review]
Looks good and thanks for the work 👍  
We still need a changelog entry to merge this though 🙂

**Comment by BobbyMcWho** [comment]
Sorry about that @st0012, been majorly busy with things. If there's any way to get this into a 5.7.1 release that would be lovely, else we can pin to a ref I suppose.

**Comment by st0012** [comment]
@BobbyMcWho I think it's a feature so it needs to wait for the next minor/major release, which will probably happen around Christmas 🙂

**Comment by BobbyMcWho** [comment]
Okay, giving it a thought I can shut off the auto instrumented one and just add a custom subscriber to our app  in the meantime, so that's fine!

**Comment by st0012** [comment]
I do want to merge it into master though so you can just use the GH source. But for some reason it doesn't allow me to merge even with all checks passing.
@sl0thentr0py Can you help me merge this? I'm not sure what's blocking it.

**Comment by sl0thentr0py** [comment]
hmm this is because danger can't update status on a forked PR
>  Warning: Running from a forked repo. Danger won’t be able to post comments and workflow status on the main repo, printing directly.


will see what to do

**Pull request merged**
