### PR TITLE
Only extend ActiveJob when it's defined

### LINKED ISSUE #1210: uninitialized constant ActiveJob
**Describe the bug**
Currently in my Rails application I don't require ActiveJob framework and on app initialization I get the error `uninitialized constant ActiveJob`.
I suppose the railtie should check if `ActiveJob::Base` is defined and then mix `Sentry::Rails::ActiveJobExtensions` to `ActiveJob::Base`

**To Reproduce**
Comment `require 'active_job/railtie'` in `config/application.rb`

**Expected behavior**
No errors

**Actual behavior**
raising of `uninitialized constant ActiveJob` error

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version: 4.1.4
 - Integration Versions:
  - Rails 6.1.1

### PR DESCRIPTION
**Pull request by st0012**
It's somewhat common for Rails users to exclude ActiveJob by manually
requiring every other components when they don't need it. So we should
detect if the ActiveJob constant is defined before extending it.

Fixes #1210

### CODE REVIEW

**Comment by croaky** [comment]
Thanks for this! I bumped into it while migrating from `sentry-raven` to `sentry-ruby` today.

Do you think you could release a patch release of this to rubygems.org?

This is working perfectly locally:

```ruby
gem "sentry-rails", github: "getsentry/sentry-ruby", glob: "sentry-rails/*.gemspec"
gem "sentry-ruby", github: "getsentry/sentry-ruby", glob: "sentry-ruby/*.gemspec"
```

But the events aren't being reported on Heroku. Wondering if it's Git-related due to some logs but, still investigating:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)
```

**Comment by st0012** [comment]
I'll release `sentry-rails 4.1.5` this week. but I think this should work

```ruby
gem "sentry-rails", github: "getsentry/sentry-ruby"
gem "sentry-ruby", github: "getsentry/sentry-ruby"
```

**Comment by st0012** [comment]
@croaky well it's been released in version 4.1.5 now 🙂

**Comment by croaky** [comment]
Thanks @st0012!

**Pull request merged**
