### PR TITLE
Cleanup development dependencies

### PR DESCRIPTION
**Pull request by st0012**
#skip-changelog

### CODE REVIEW

**Comment by st0012** [comment]
The Ruby head builds are failing because of [nio4r's compilation issue](https://github.com/socketry/nio4r/issues/299).

**Comment by st0012** [comment]
@sl0thentr0py BTW I'm thinking not running the SDK against `ruby-head` until probably November because currently it creates more friction than benefit.

**Comment by sl0thentr0py** [comment]
yea fine with me

**Comment by st0012** [comment]
ping @sl0thentr0py

**Review by sl0thentr0py — APPROVED** [review]

**Pull request merged**
