### PR TITLE
Remove resque redis pin since upstream is fixed

### PR DESCRIPTION
**Pull request by sl0thentr0py**
https://github.com/resque/resque/pull/1828
https://github.com/resque/resque/pull/1822
https://github.com/resque/resque/releases/tag/v2.4.0

### CODE REVIEW

**Comment by sl0thentr0py** [comment]
hmm still segfaulting somewhere else :(

**Comment by st0012** [comment]
This is actually an issue between Ruby 2.6 & `debug` & `redis-client`. I think it's probably Ruby 2.6's issue. I can reproduce it with:

```rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  ruby "~> 2.6.6"

  gem "debug"
  gem "redis-client"
end
```

This change should workaround the issue:

```diff
--- a/sentry-resque/spec/spec_helper.rb
+++ b/sentry-resque/spec/spec_helper.rb
@@ -1,6 +1,6 @@
 require "bundler/setup"
 require "pry"
-require "debug" if RUBY_VERSION.to_f >= 2.6
+require "debug" if RUBY_VERSION.to_f >= 2.7

 require "resque"
```

**Comment by st0012** [comment]
I opened an issue for the crash here: https://github.com/redis-rb/redis-client/issues/47
And the latest failure seems to be caused by Rack 3. We'll need to start testing multiple Rack versions I think.

**Comment by sl0thentr0py** [comment]
ah yes Rack 3 makes sense, thx for the heads up.
Will try to fix in another PR in a bit.

**Comment by st0012** [comment]
`redis-client` has fixed the issue so we probably wont need the workaround either. Perhaps we can drop the version pin in the Rack PR instead?

**Pull request closed without merging**
